#!/usr/bin/env bash
# This script displays information about subdomains of a domain.

# Function to get record information for a subdomain
get_record_info() {
    domain="$1"
    subdomain="$2"
    destination=$(dig +short "$subdomain.$domain" | awk 'NR==1')
    echo "The subdomain $subdomain is a A record and points to $destination"
}

# Function to display information for default subdomains
display_default_subdomains_info() {
    domain="$1"
    subdomains=("www" "lb-01" "web-01" "web-02")
    for subdomain in "${subdomains[@]}"; do
        get_record_info "$domain" "$subdomain"
    done
}

# Main script
main() {
    domain="$1"
    subdomain="$2"

    if [ -z "$subdomain" ]; then
        display_default_subdomains_info "$domain"
    else
        get_record_info "$domain" "$subdomain"
    fi
}

# Execute main with provided arguments
main "$@"
