#!/usr/bin/env bash
# This script transfers a file from a client machine to a server using SCP.

# Check if the correct number of parameters is passed
if [ "$#" -ne 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

# Transfer the file using scp to the server's home directory
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username"@"$server_ip":~/ || exit 1

echo "File transferred successfully to $username@$server_ip:~/"
exit 0