#!/usr/bin/env bash
# This script configures Nginx to redirect a specific URL.

# Check if Nginx is installed
if ! command -v nginx &> /dev/null; then
    echo "Nginx is not installed. Installing Nginx..."
    apt-get update
    apt-get install -y nginx
fi

# Define the redirect configuration
redirect_config="\
server {
    listen 80;
    listen [::]:80;
    server_name _;

    rewrite ^/redirect_me https://youtube.com/@AfroPlayerOne?si=BueiWNt5G6RIRvJe permanent;
    
    location /redirect_me {
        return 301 https://youtube.com/@AfroPlayerOne?si=BueiWNt5G6RIRvJe;
    }
}
"

# Backup the default Nginx configuration file
cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Add the redirect configuration to Nginx
echo "$redirect_config" > /etc/nginx/sites-available/default

# Test Nginx configuration for syntax errors
nginx -t

# Reload Nginx to apply the changes
sudo service nginx restart

echo "Nginx redirection configured successfully!"
