#!/usr/bin/env bash
# This script configures Nginx to include a custom HTTP response header (X-Served-By)

# Install Nginx if not already installed
if ! command -v nginx &> /dev/null; then
    apt-get update
    apt-get install -y nginx
fi

# Configure Nginx to include the custom header
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location / {
        add_header X-Served-By 519510-web-01;
        root /var/www/html;
        index index.html index.htm;
    }
}" | sudo tee /etc/nginx/sites-available/default

if ! command curl &> dev/null; then
    apt-get install -y curl
fi

curl -sI 3.80.19.156 | grep X-Served-By

curl -sI 54.237.70.145 | grep X-Served-By

# Test Nginx configuration for syntax errors
nginx -t

# Reload Nginx to apply the changes
service nginx reload
