#!/usr/bin/env bash
# Script to configure HaProxy

# Function to configure HAProxy
configure_haproxy() {
    # Check if the HAProxy configuration file exists
    haproxy_cfg="/etc/haproxy/haproxy.cfg"
    if [ -f "$haproxy_cfg" ]; then
        # Backup the original HAProxy configuration file
        sudo cp "$haproxy_cfg" "$haproxy_cfg.bak"
        
        # Append frontend and backend configurations
        cat << EOF | sudo tee -a "$haproxy_cfg" > /dev/null
frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 519510-web-01:80 check
    server web-02 519510-web-02:80 check
EOF

        # Restart HAProxy service
        sudo systemctl restart haproxy
    else
        echo "HAProxy configuration file not found: $haproxy_cfg" >&2
        exit 1
    fi
}

# Main function
main() {
    configure_haproxy
}

main