#!/usr/bin/env bash
# Script to configure Nginx with a custom HTTP response header
                                                                                                                            
sudo rm /etc/nginx/sites-enabled/default;

sudo ln -s /etc/nginx/sites-available/default default;

service nginx restart 