#!/usr/bin/env bash
# Script to configure Nginx with a custom HTTP response header                                                                                                                          
sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo kill -9 "$(cat /run/nginx.pid)"