#!/usr/bin/env bash
# This script configures Nginx to run as the nginx user and listen on port 8080

# Allow everyone to modify the file
chmod 777 /etc/nginx/nginx.conf

# Modify the default server block to listen on port 8080
sed -i 's/80/8080/g' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo -u nginx service nginx restart
