#!/usr/bin/env bash
# This script configures Nginx to run as the nginx user and listen on port 8080

# Make the file read and writeable for everyone
chmod 777 /etc/nginx/nginx.conf

# update listening ports
sed -i 's/80/8080/g' /etc/nginx/sites-available/default

# restart nginx as nginx
sudo -u nginx service nginx restart