#!/usr/bin/env bash
# This file shortens the code from previous question
sudo -u "$1" whoami
chmod 777 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
