#!/bin/bash

# Name of the private key
private_key="school"

# Number of bits for the RSA key
key_bits=4096

# Passphrase for the key
passphrase="betty"

# Generate the RSA key pair
ssh-keygen -t rsa -b "$key_bits" -N "$passphrase" -f "$private_key"

# Display information about the generated keys
echo "Generating public/private rsa key pair."
echo "Your identification has been saved in $private_key."
echo "Your public key has been saved in $private_key.pub."
echo "The key fingerprint is:"
ssh-keygen -l -E md5 -f "$private_key"
echo "The key's randomart image is:"
ssh-keygen -l -v -E md5 -f "$private_key"
